name = "Fairburn Pack"
author = "Ryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60152fc95d89b9ce2e66d722c51e4f9b52710e3efb2c8d041484323cf8c489cc"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
