name = "Fairburn Pack"
author = "Ryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "121808b8c0e0d23d333462ef08bc924efd54a93514273199b43e4faa74b06c1a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.68"
