name = "Fairburn Pack"
author = "Ryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca8c776f07147717968308d9202507ab2b9fbb893f5ad5fc68357ac832e1c520"

[versions]
forge = "52.0.19"
minecraft = "1.21.1"
