name = "Fairburn Pack"
author = "Ryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a43e22c3b94a0dc5eb9b34f25677f3b8d6f1be590c09112a75b26bb049e5e1cf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.68"
