name = "Fairburn Pack"
author = "Ryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c60cd1209fd2d5972fbce38c6a3e4ec2c13d574caa48a47937c96ad22d7a260"

[versions]
minecraft = "1.21.1"
neoforge = "52.0.19"
