name = "Fairburn Pack"
author = "Ryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "522d979478820f3d7c10bcf633a7921e048e753f2c1b56e2fa7a6e9f6ba0a9c6"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
