name = "Fairburn Pack"
author = "Ryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dc706746a33f56ace84a36779009d3b1aebe6219a3d7aaa4a4dcde5ae7d3f16"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.68"
