name = "Fairburn Pack"
author = "Ryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a699e5b964ad49ef901d6cda081b882d15d60ad66ff7d0b3374dd028386876f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.68"
