name = "Fairburn Pack"
author = "Ryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b820e428b1187e225582d8006bad7fe8b638879a140d937bffc5ca434131559e"

[versions]
forge = "47.1.106"
minecraft = "1.20.1"
