name = "Fairburn Pack"
author = "Ryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d02c9b796bf7166ae903eec16dda5e2660611a77b02eecb90a0466f71cca3038"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
