name = "Fairburn Pack"
author = "Ryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea2837256b0eee0e95aa24fe680513a19c04f24deaa121cb0934cf6241f83afb"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
